import React, { createContext, useState, useEffect, useContext } from 'react';
import PropTypes from 'prop-types';

export const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    navHome: "Home", navLighthouse: "Lighthouse", navServices: "Services", navContact: "Contact",
    // Footer (App.jsx)
    footerAbout: "Analyze and improve your website's performance with our comprehensive tools.",
    footerQuickLinks: "Quick Links", footerContactTitle: "Contact",
    footerContactText: "Have questions? Reach out to us for support and inquiries.",
    footerContactBtn: "Contact Us", footerRights: "Web Scanner. All rights reserved.",
    // WebsiteGrader.jsx
    title: "Web Scanner",
    subtitle: "Grade your website in seconds. Then learn how to improve it for free.",
    urlPlaceholder: "https://example.com", emailPlaceholder: "Enter Your Email",
    privacyText: "We are committed to your privacy. Mycto uses the information you provide to us to contact you about our relevant content, products, and services. You may unsubscribe from these communications at any time. For more information, check out our",
    privacyPolicy: "Privacy Policy", getScore: "Get your score", analyzing: "Analyzing...",
    featuresTitle: "Get Your Website Rating in Seconds",
    featuresSubtitle: "Website grader tools make understanding website performance easy. Learn about your page performance, security, SEO, and mobile experience.",
    performance: "Performance", performanceDesc: "Analyze your website's speed and performance metrics",
    security: "Security", securityDesc: "Check your website's security and best practices",
    seo: "SEO", seoDesc: "Evaluate your search engine optimization",
    mobile: "Mobile", mobileDesc: "Test your website's mobile responsiveness",
    realTimeAnalysis: "Real-time Analysis",
    // Contact.jsx
    contactUs: "Contact Us", contactHeading: "We'd love to hear from you!",
    contactSubtext: "Have questions about our Web Scanner? Want to improve your website's performance, SEO, or best practices? Reach out to us!",
    contactName: "Name", contactNamePlaceholder: "Your name",
    contactEmail: "Email", contactEmailPlaceholder: "john@example.com",
    contactMobile: "Mobile Number", contactMobilePlaceholder: "1234567890",
    contactMessage: "Message", contactMessagePlaceholder: "Type your message here.",
    contactSend: "Send Message", contactSending: "Sending...",
    contactSuccess: "Message Sent!", contactSuccessDesc: "Thank you for your message. We'll get back to you soon!",
    contactError: "Error Sending Message", contactErrorDesc: "Something went wrong. Please try again later.",
    // Servicepage.jsx
    servicesTitle: "Our Services",
    servicesSubtitle: "Comprehensive web solutions to elevate your online presence and drive business growth.",
    serviceWebDev: "Web Development", serviceWebDevDesc: "Custom website design and development tailored to your business needs.",
    servicePerfOpt: "Performance Optimization", servicePerfOptDesc: "Improve website speed, user experience, and search engine rankings.",
    serviceSecAudit: "Security Audit", serviceSecAuditDesc: "Comprehensive security analysis and protection strategies.",
    serviceSEO: "SEO Services", serviceSEODesc: "Enhance your online visibility and attract more organic traffic.",
    serviceResponsive: "Responsive Design", serviceResponsiveDesc: "Ensure your website looks great on all devices and screen sizes.",
    serviceGlobal: "Global Accessibility", serviceGlobalDesc: "Make your website accessible and inclusive for all users.",
    servicesCtaTitle: "Ready to Transform Your Web Presence?",
    servicesCtaBtn: "Schedule a Consultation",
    // Lighthouse.jsx
    lighthouseNoData: "No Analysis Data Found", lighthouseBack: "Back to Home",
    lighthouseBackShort: "Back", lighthouseAnalysis: "Analysis Results",
    lighthouseContactMe: "Contact Me", lighthouseOverallScore: "Overall Score",
    lighthouseFooterRights: "Web Scanner. All rights reserved.",
  },
  de: {
    navHome: "Startseite", navLighthouse: "Lighthouse", navServices: "Dienstleistungen", navContact: "Kontakt",
    footerAbout: "Analysieren und verbessern Sie die Leistung Ihrer Website mit unseren Tools.",
    footerQuickLinks: "Schnelllinks", footerContactTitle: "Kontakt",
    footerContactText: "Haben Sie Fragen? Kontaktieren Sie uns für Support.", footerContactBtn: "Kontaktiere uns",
    footerRights: "Web Scanner. Alle Rechte vorbehalten.",
    title: "Web Scanner",
    subtitle: "Bewerten Sie Ihre Website in Sekunden. Lernen Sie kostenlos, wie Sie sie verbessern können.",
    urlPlaceholder: "https://beispiel.de", emailPlaceholder: "E-Mail eingeben",
    privacyText: "Wir verpflichten uns zu Ihrer Privatsphäre. Sie können diese Kommunikation jederzeit abbestellen. Weitere Informationen:",
    privacyPolicy: "Datenschutzerklärung", getScore: "Bewertung erhalten", analyzing: "Analysiere...",
    featuresTitle: "Erhalten Sie Ihre Website-Bewertung in Sekunden",
    featuresSubtitle: "Erfahren Sie mehr über Ihre Seitenleistung, Sicherheit, SEO und mobile Erfahrung.",
    performance: "Leistung", performanceDesc: "Analysieren Sie Geschwindigkeit und Leistungsmetriken",
    security: "Sicherheit", securityDesc: "Überprüfen Sie die Sicherheit und Best Practices",
    seo: "SEO", seoDesc: "Bewerten Sie Ihre Suchmaschinenoptimierung",
    mobile: "Mobil", mobileDesc: "Testen Sie die mobile Reaktionsfähigkeit", realTimeAnalysis: "Echtzeit-Analyse",
    contactUs: "Kontaktiere uns", contactHeading: "Wir würden gerne von Ihnen hören!",
    contactSubtext: "Haben Sie Fragen zu unserem Web Scanner? Erreichen Sie uns!",
    contactName: "Name", contactNamePlaceholder: "Ihr Name",
    contactEmail: "E-Mail", contactEmailPlaceholder: "max@beispiel.de",
    contactMobile: "Handynummer", contactMobilePlaceholder: "1234567890",
    contactMessage: "Nachricht", contactMessagePlaceholder: "Schreiben Sie Ihre Nachricht hier.",
    contactSend: "Nachricht senden", contactSending: "Senden...",
    contactSuccess: "Nachricht gesendet!", contactSuccessDesc: "Danke für Ihre Nachricht. Wir melden uns bald!",
    contactError: "Fehler beim Senden", contactErrorDesc: "Etwas ist schiefgelaufen. Bitte versuchen Sie es später.",
    servicesTitle: "Unsere Dienstleistungen",
    servicesSubtitle: "Umfassende Web-Lösungen zur Steigerung Ihrer Online-Präsenz.",
    serviceWebDev: "Webentwicklung", serviceWebDevDesc: "Maßgeschneiderte Website-Entwicklung für Ihr Unternehmen.",
    servicePerfOpt: "Leistungsoptimierung", servicePerfOptDesc: "Verbessern Sie Websitegeschwindigkeit und Nutzererfahrung.",
    serviceSecAudit: "Sicherheitsaudit", serviceSecAuditDesc: "Umfassende Sicherheitsanalyse und Schutzstrategien.",
    serviceSEO: "SEO-Dienste", serviceSEODesc: "Verbessern Sie Ihre Online-Sichtbarkeit.",
    serviceResponsive: "Responsives Design", serviceResponsiveDesc: "Ihre Website sieht auf allen Geräten großartig aus.",
    serviceGlobal: "Globale Zugänglichkeit", serviceGlobalDesc: "Machen Sie Ihre Website für alle Nutzer zugänglich.",
    servicesCtaTitle: "Bereit, Ihre Web-Präsenz zu transformieren?", servicesCtaBtn: "Beratung vereinbaren",
    lighthouseNoData: "Keine Analysedaten gefunden", lighthouseBack: "Zurück zur Startseite",
    lighthouseBackShort: "Zurück", lighthouseAnalysis: "Analyseergebnisse",
    lighthouseContactMe: "Kontaktiere mich", lighthouseOverallScore: "Gesamtpunktzahl",
    lighthouseFooterRights: "Web Scanner. Alle Rechte vorbehalten.",
  },
  es: {
    navHome: "Inicio", navLighthouse: "Lighthouse", navServices: "Servicios", navContact: "Contacto",
    footerAbout: "Analice y mejore el rendimiento de su sitio web con nuestras herramientas.",
    footerQuickLinks: "Enlaces rápidos", footerContactTitle: "Contacto",
    footerContactText: "¿Tiene preguntas? Contáctenos.", footerContactBtn: "Contáctenos",
    footerRights: "Web Scanner. Todos los derechos reservados.",
    title: "Web Scanner", subtitle: "Califica tu sitio web en segundos. Aprende a mejorarlo gratis.",
    urlPlaceholder: "https://ejemplo.com", emailPlaceholder: "Introduce tu correo",
    privacyText: "Estamos comprometidos con tu privacidad. Puedes cancelar la suscripción en cualquier momento. Revisa nuestra",
    privacyPolicy: "Política de privacidad", getScore: "Obtener calificación", analyzing: "Analizando...",
    featuresTitle: "Obtén la calificación de tu sitio en segundos",
    featuresSubtitle: "Aprende sobre el rendimiento, seguridad, SEO y experiencia móvil.",
    performance: "Rendimiento", performanceDesc: "Analiza la velocidad y métricas de rendimiento",
    security: "Seguridad", securityDesc: "Revisa la seguridad de tu sitio web",
    seo: "SEO", seoDesc: "Evalúa tu optimización para motores de búsqueda",
    mobile: "Móvil", mobileDesc: "Prueba la capacidad de respuesta móvil", realTimeAnalysis: "Análisis en tiempo real",
    contactUs: "Contáctenos", contactHeading: "¡Nos encantaría saber de ti!",
    contactSubtext: "¿Tienes preguntas sobre nuestro Web Scanner? ¡Contáctanos!",
    contactName: "Nombre", contactNamePlaceholder: "Tu nombre",
    contactEmail: "Correo", contactEmailPlaceholder: "juan@ejemplo.com",
    contactMobile: "Número móvil", contactMobilePlaceholder: "1234567890",
    contactMessage: "Mensaje", contactMessagePlaceholder: "Escribe tu mensaje aquí.",
    contactSend: "Enviar mensaje", contactSending: "Enviando...",
    contactSuccess: "¡Mensaje enviado!", contactSuccessDesc: "Gracias por tu mensaje. ¡Te responderemos pronto!",
    contactError: "Error al enviar", contactErrorDesc: "Algo salió mal. Por favor intenta de nuevo.",
    servicesTitle: "Nuestros Servicios",
    servicesSubtitle: "Soluciones web para elevar tu presencia en línea.",
    serviceWebDev: "Desarrollo Web", serviceWebDevDesc: "Diseño y desarrollo de sitios web personalizados.",
    servicePerfOpt: "Optimización de Rendimiento", servicePerfOptDesc: "Mejora la velocidad y experiencia del usuario.",
    serviceSecAudit: "Auditoría de Seguridad", serviceSecAuditDesc: "Análisis de seguridad y estrategias de protección.",
    serviceSEO: "Servicios SEO", serviceSEODesc: "Mejora tu visibilidad en línea.",
    serviceResponsive: "Diseño Responsivo", serviceResponsiveDesc: "Tu sitio se verá bien en todos los dispositivos.",
    serviceGlobal: "Accesibilidad Global", serviceGlobalDesc: "Haz tu sitio web accesible para todos.",
    servicesCtaTitle: "¿Listo para transformar tu presencia web?", servicesCtaBtn: "Programar consulta",
    lighthouseNoData: "No se encontraron datos de análisis", lighthouseBack: "Volver al inicio",
    lighthouseBackShort: "Volver", lighthouseAnalysis: "Resultados del análisis",
    lighthouseContactMe: "Contáctame", lighthouseOverallScore: "Puntuación general",
    lighthouseFooterRights: "Web Scanner. Todos los derechos reservados.",
  },
  fr: {
    navHome: "Accueil", navLighthouse: "Lighthouse", navServices: "Services", navContact: "Contact",
    footerAbout: "Analysez et améliorez les performances de votre site Web avec nos outils.",
    footerQuickLinks: "Liens rapides", footerContactTitle: "Contact",
    footerContactText: "Des questions ? Contactez-nous.", footerContactBtn: "Nous contacter",
    footerRights: "Web Scanner. Tous droits réservés.",
    title: "Web Scanner", subtitle: "Évaluez votre site web en quelques secondes. Apprenez à l'améliorer gratuitement.",
    urlPlaceholder: "https://exemple.fr", emailPlaceholder: "Entrez votre email",
    privacyText: "Nous respectons votre confidentialité. Vous pouvez vous désabonner à tout moment. Consultez notre",
    privacyPolicy: "Politique de confidentialité", getScore: "Obtenir le score", analyzing: "Analyse en cours...",
    featuresTitle: "Obtenez la note de votre site en quelques secondes",
    featuresSubtitle: "Découvrez les performances, la sécurité, le SEO et l'expérience mobile.",
    performance: "Performances", performanceDesc: "Analysez la vitesse et les performances",
    security: "Sécurité", securityDesc: "Vérifiez la sécurité et les bonnes pratiques",
    seo: "SEO", seoDesc: "Évaluez l'optimisation pour les moteurs de recherche",
    mobile: "Mobile", mobileDesc: "Testez la réactivité mobile", realTimeAnalysis: "Analyse en temps réel",
    contactUs: "Nous contacter", contactHeading: "Nous serions ravis d'avoir de vos nouvelles!",
    contactSubtext: "Des questions sur notre Web Scanner ? Contactez-nous!",
    contactName: "Nom", contactNamePlaceholder: "Votre nom",
    contactEmail: "Email", contactEmailPlaceholder: "jean@exemple.fr",
    contactMobile: "Numéro mobile", contactMobilePlaceholder: "1234567890",
    contactMessage: "Message", contactMessagePlaceholder: "Tapez votre message ici.",
    contactSend: "Envoyer le message", contactSending: "Envoi en cours...",
    contactSuccess: "Message envoyé!", contactSuccessDesc: "Merci pour votre message. Nous vous répondrons bientôt!",
    contactError: "Erreur d'envoi", contactErrorDesc: "Quelque chose s'est mal passé. Veuillez réessayer.",
    servicesTitle: "Nos Services",
    servicesSubtitle: "Solutions web complètes pour améliorer votre présence en ligne.",
    serviceWebDev: "Développement Web", serviceWebDevDesc: "Conception et développement de sites web sur mesure.",
    servicePerfOpt: "Optimisation des performances", servicePerfOptDesc: "Améliorez la vitesse et l'expérience utilisateur.",
    serviceSecAudit: "Audit de sécurité", serviceSecAuditDesc: "Analyse de sécurité complète et stratégies de protection.",
    serviceSEO: "Services SEO", serviceSEODesc: "Améliorez votre visibilité en ligne.",
    serviceResponsive: "Design Responsive", serviceResponsiveDesc: "Votre site est magnifique sur tous les appareils.",
    serviceGlobal: "Accessibilité Globale", serviceGlobalDesc: "Rendez votre site accessible à tous.",
    servicesCtaTitle: "Prêt à transformer votre présence web?", servicesCtaBtn: "Planifier une consultation",
    lighthouseNoData: "Aucune donnée d'analyse trouvée", lighthouseBack: "Retour à l'accueil",
    lighthouseBackShort: "Retour", lighthouseAnalysis: "Résultats de l'analyse",
    lighthouseContactMe: "Contactez-moi", lighthouseOverallScore: "Score global",
    lighthouseFooterRights: "Web Scanner. Tous droits réservés.",
  },
  ja: {
    navHome: "ホーム", navLighthouse: "Lighthouse", navServices: "サービス", navContact: "連絡先",
    footerAbout: "当社の包括的なツールでウェブサイトのパフォーマンスを分析および改善します。",
    footerQuickLinks: "クイックリンク", footerContactTitle: "連絡先",
    footerContactText: "ご質問がありますか？サポートやお問い合わせはこちらから。", footerContactBtn: "お問い合わせ",
    footerRights: "Web Scanner. 無断複写・転載を禁じます。",
    title: "Web Scanner", subtitle: "数秒でウェブサイトを評価。無料で改善方法を学びましょう。",
    urlPlaceholder: "https://example.jp", emailPlaceholder: "メールアドレスを入力",
    privacyText: "プライバシーを尊重しています。いつでも配信停止可能です。詳しくは",
    privacyPolicy: "プライバシーポリシー", getScore: "スコアを取得", analyzing: "分析中...",
    featuresTitle: "数秒でウェブサイトの評価を取得",
    featuresSubtitle: "パフォーマンス、セキュリティ、SEO、モバイルエクスペリエンスについて学びましょう。",
    performance: "パフォーマンス", performanceDesc: "ウェブサイトの速度とパフォーマンスを分析",
    security: "セキュリティ", securityDesc: "セキュリティとベストプラクティスを確認",
    seo: "SEO", seoDesc: "検索エンジン最適化を評価",
    mobile: "モバイル", mobileDesc: "モバイルのレスポンシブ性をテスト", realTimeAnalysis: "リアルタイム分析",
    contactUs: "お問い合わせ", contactHeading: "ぜひご連絡ください！",
    contactSubtext: "Web Scannerについてご質問はありますか？お気軽にどうぞ！",
    contactName: "お名前", contactNamePlaceholder: "お名前",
    contactEmail: "メール", contactEmailPlaceholder: "taro@example.jp",
    contactMobile: "携帯番号", contactMobilePlaceholder: "1234567890",
    contactMessage: "メッセージ", contactMessagePlaceholder: "メッセージをここに入力してください。",
    contactSend: "送信", contactSending: "送信中...",
    contactSuccess: "送信完了！", contactSuccessDesc: "メッセージありがとうございます。近日中にご返信します！",
    contactError: "送信エラー", contactErrorDesc: "問題が発生しました。後でもう一度お試しください。",
    servicesTitle: "サービス一覧",
    servicesSubtitle: "オンラインプレゼンスを高め、ビジネス成長を促進する総合Webソリューション。",
    serviceWebDev: "ウェブ開発", serviceWebDevDesc: "ビジネスニーズに合わせたカスタムウェブサイト開発。",
    servicePerfOpt: "パフォーマンス最適化", servicePerfOptDesc: "速度とユーザー体験を改善。",
    serviceSecAudit: "セキュリティ監査", serviceSecAuditDesc: "包括的なセキュリティ分析と保護戦略。",
    serviceSEO: "SEOサービス", serviceSEODesc: "オンライン可視性を向上させる。",
    serviceResponsive: "レスポンシブデザイン", serviceResponsiveDesc: "すべてのデバイスで美しく表示。",
    serviceGlobal: "グローバルアクセシビリティ", serviceGlobalDesc: "すべてのユーザーがアクセスできるウェブサイトに。",
    servicesCtaTitle: "Webプレゼンスを変革する準備はできましたか？", servicesCtaBtn: "相談を予約する",
    lighthouseNoData: "分析データが見つかりません", lighthouseBack: "ホームに戻る",
    lighthouseBackShort: "戻る", lighthouseAnalysis: "分析結果",
    lighthouseContactMe: "お問い合わせ", lighthouseOverallScore: "総合スコア",
    lighthouseFooterRights: "Web Scanner. 無断複写・転載を禁じます。",
  },
  pt: {
    navHome: "Início", navLighthouse: "Lighthouse", navServices: "Serviços", navContact: "Contato",
    footerAbout: "Analise e melhore o desempenho do seu site com nossas ferramentas.",
    footerQuickLinks: "Links rápidos", footerContactTitle: "Contato",
    footerContactText: "Tem perguntas? Entre em contato.", footerContactBtn: "Contate-Nos",
    footerRights: "Web Scanner. Todos os direitos reservados.",
    title: "Web Scanner", subtitle: "Avalie seu site em segundos. Aprenda como melhorá-lo de graça.",
    urlPlaceholder: "https://exemplo.com.br", emailPlaceholder: "Digite seu e-mail",
    privacyText: "Estamos comprometidos com sua privacidade. Você pode cancelar a inscrição a qualquer momento. Confira nossa",
    privacyPolicy: "Política de Privacidade", getScore: "Obter pontuação", analyzing: "Analisando...",
    featuresTitle: "Obtenha a classificação do seu site em segundos",
    featuresSubtitle: "Saiba mais sobre desempenho, segurança, SEO e experiência móvel.",
    performance: "Desempenho", performanceDesc: "Analise a velocidade e métricas do seu site",
    security: "Segurança", securityDesc: "Verifique a segurança e as melhores práticas",
    seo: "SEO", seoDesc: "Avalie a otimização do mecanismo de busca",
    mobile: "Móvel", mobileDesc: "Teste a capacidade de resposta móvel", realTimeAnalysis: "Análise em tempo real",
    contactUs: "Contate-Nos", contactHeading: "Adoraríamos ouvir de você!",
    contactSubtext: "Tem perguntas sobre o Web Scanner? Entre em contato!",
    contactName: "Nome", contactNamePlaceholder: "Seu nome",
    contactEmail: "E-mail", contactEmailPlaceholder: "joao@exemplo.com.br",
    contactMobile: "Número móvel", contactMobilePlaceholder: "1234567890",
    contactMessage: "Mensagem", contactMessagePlaceholder: "Digite sua mensagem aqui.",
    contactSend: "Enviar mensagem", contactSending: "Enviando...",
    contactSuccess: "Mensagem enviada!", contactSuccessDesc: "Obrigado pela sua mensagem. Responderemos em breve!",
    contactError: "Erro ao enviar", contactErrorDesc: "Algo deu errado. Por favor, tente novamente.",
    servicesTitle: "Nossos Serviços",
    servicesSubtitle: "Soluções web abrangentes para elevar sua presença online.",
    serviceWebDev: "Desenvolvimento Web", serviceWebDevDesc: "Design e desenvolvimento de sites personalizados.",
    servicePerfOpt: "Otimização de Desempenho", servicePerfOptDesc: "Melhore velocidade e experiência do usuário.",
    serviceSecAudit: "Auditoria de Segurança", serviceSecAuditDesc: "Análise de segurança e estratégias de proteção.",
    serviceSEO: "Serviços de SEO", serviceSEODesc: "Melhore sua visibilidade online.",
    serviceResponsive: "Design Responsivo", serviceResponsiveDesc: "Seu site fica ótimo em todos os dispositivos.",
    serviceGlobal: "Acessibilidade Global", serviceGlobalDesc: "Torne seu site acessível para todos.",
    servicesCtaTitle: "Pronto para transformar sua presença web?", servicesCtaBtn: "Agendar consulta",
    lighthouseNoData: "Nenhum dado de análise encontrado", lighthouseBack: "Voltar ao início",
    lighthouseBackShort: "Voltar", lighthouseAnalysis: "Resultados da análise",
    lighthouseContactMe: "Contate-me", lighthouseOverallScore: "Pontuação geral",
    lighthouseFooterRights: "Web Scanner. Todos os direitos reservados.",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('preferredLanguage');
    if (saved && translations[saved]) setLanguage(saved);
  }, []);

  const handleLanguageChange = (value) => {
    setLanguage(value);
    localStorage.setItem('preferredLanguage', value);
  };

  const t = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleLanguageChange, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

LanguageProvider.propTypes = { children: PropTypes.node.isRequired };

export const useLanguage = () => useContext(LanguageContext);
